In [1]:
import numpy as np

# Question 1

In [26]:
x1 = np.array([0.5,0.2,0.8])
x2 = np.array([0.3,0.7,0.2])
x3 = np.array([0.6,0.1,0.4])
x4 = np.array([0.1,0.9,0.5])

# Part a

In [28]:
s1 = np.dot(x1,x3)
s2 = np.dot(x2,x3)
s3 = np.dot(x3,x3)
print(s1,s2,s3)
result = [s1,s2,s3]

0.6400000000000001 0.33 0.53


# Part b

In [30]:
result = np.array(result)
softmax_result = np.exp(result)/np.sum(np.exp(result))
print(softmax_result)

[0.3803321  0.27895342 0.34071448]


# Part c

In [31]:
y_3 = softmax_result[0]*x1 + softmax_result[1]*x2 + softmax_result[2]*x3
print(y_3)

[0.47828076 0.30540526 0.49634216]


# Question 2

In [14]:
K = np.eye(2)
Q = np.eye(2)*2
V = np.eye(2)*3
print(K.shape,Q.shape,V.shape)

(2, 2) (2, 2) (2, 2)


In [15]:
x1 = np.array([0.5,0.5])
x2 = np.array([1,1])
x3 = np.array([0.75,0.75])


# Part a

In [16]:
k1 = np.dot(K,x1)
v1 = np.dot(V,x1)
q1 = np.dot(Q,x1)
print(k1,v1,q1)

[0.5 0.5] [1.5 1.5] [1. 1.]


In [17]:
k2 = np.dot(K,x2)
v2 = np.dot(V,x2)
q2 = np.dot(Q,x2)
print(k2,v2,q2)

[1. 1.] [3. 3.] [2. 2.]


In [18]:
k3 = np.dot(K,x3)
v3 = np.dot(V,x3)
q3 = np.dot(Q,x3)
print(k3,v3,q3)

[0.75 0.75] [2.25 2.25] [1.5 1.5]


# Part b

In [19]:
scores = np.zeros((3,3))

In [20]:
d = dict()
d['q1'] = q1
d['q2'] = q2
d['q3'] = q1
d['k1'] = k1
d['k2'] = k2
d['k3'] = k3
d['v1'] = v1
d['v2'] = v2
d['v3'] = v3

In [21]:
for i in range(1,4):
  for j in range(1,4):
    if j <=i:
      scores[i-1][j-1] = np.dot(d[f'q{i}'],d[f'k{j}'])/np.sqrt(2)
    else:
      scores[i-1][j-1] = -float('inf')

In [22]:
scores

array([[0.70710678,       -inf,       -inf],
       [1.41421356, 2.82842712,       -inf],
       [0.70710678, 1.41421356, 1.06066017]])

# Part c

In [23]:
softmax = np.exp(scores)/np.sum(np.exp(scores),axis=1,keepdims=True)

In [24]:
softmax

array([[1.        , 0.        , 0.        ],
       [0.19557032, 0.80442968, 0.        ],
       [0.22460634, 0.45552749, 0.31986617]])

# Part d

In [25]:
for i in range(3):
  new_value = np.zeros(2)
  for j in range(3):
    print(f'a_{i+1}{j+1} v{j+1}')
    new_value += softmax[i][j] * d[f'v{j+1}']
  print(new_value)



a_11 v1
a_12 v2
a_13 v3
[1.5 1.5]
a_21 v1
a_22 v2
a_23 v3
[2.70664452 2.70664452]
a_31 v1
a_32 v2
a_33 v3
[2.42319086 2.42319086]
