In [1]:
import numpy as np

In [2]:
mask_key = np.array([0.4,0.6,0.2])
mask_query = np.array([0.7,0.2,0.5])
mask_value = np.array([0.8,0.5,0.9])

In [3]:
Deep_key = np.array([0.2,0.5,0.7])
Deep_query = np.array([0.1,0.2,0.3])
Deep_value = np.array([0.3,0.4,0.5])

In [4]:
Learning_key = np.array([0.6,0.3,0.9])
Learning_query = np.array([0.4,0.5,0.6])
Learning_value = np.array([0.6,0.7,0.8])

In [5]:
is_key = np.array([0.1,0.8,0.4])
is_query = np.array([0.7,0.4,0.1])
is_value = np.array([0.2,0.9,0.6])

# Part a

In [10]:
s1 = np.dot(mask_query,Deep_key)
s2 = np.dot(mask_query,Learning_key)
s3 = np.dot(mask_query,is_key)
s4 = np.dot(mask_query,mask_key)
print(s1,s2,s3,s4)

0.59 0.9299999999999999 0.43000000000000005 0.5


# Part b

In [11]:
result = np.array([s1,s2,s3,s4])/np.sqrt(3)
print(result)

[0.34063666 0.53693575 0.24826062 0.28867513]


# Part c

In [9]:
softmax_result = np.exp(result)/np.sum(np.exp(result),keepdims=True)
softmax_result

array([0.24521714, 0.29840248, 0.22357972, 0.23280066])

# Part d

In [12]:
y_i = softmax_result[0]*Deep_value + softmax_result[1]*Learning_value + softmax_result[2]*is_value+softmax_result[3]*mask_value
print(y_i)

[0.4835631  0.62459067 0.70499898]


# Part e

In [16]:
logits = np.array([1.8,1.7,1.6,0.78,3.2])
softmax_logits = np.exp(logits)/np.sum(np.exp(logits),keepdims=True)
print(softmax_logits)
print(np.argmax(softmax_logits))
# Index 4 has the highest value and it corresponds to boring in the vocabulary so the predicted token will be boring

[0.14006852 0.12673924 0.1146784  0.050508   0.56800585]
4


# Part f

In [17]:
# Actual token = Fun and Predict token = Boring
loss = -np.log(softmax_logits[3])
print(loss)

2.9856235676290535
